name: .NET CI QuickPulse
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests (TRX)
      run: dotnet test --logger "trx;LogFileName=test.trx" --results-directory TestResults
    - name: Install ReportUnit
      run: dotnet tool update -g reportunit
    - name: Generate HTML from TRX
      run: |
        reportunit "TestResults" "TestResultsHtml"
        ls -la TestResultsHtml
    - name: Upload HTML report (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: test-report-html
        path: TestResultsHtml/
    - name: Complexity analysis using SCC
      uses: hdmsantander/scc-docker-action@3.0
      with:
        args: --exclude-dir obj --exclude-dir bin --include-ext cs --no-cocomo QuickPulse/
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: TestResultsHtml
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
          
