name: .NET CI QuickPulse
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: XUnit Viewer
      uses: AutoModality/action-xunit-viewer@v1.0.1
      # with:
      # File/Folder of test results
        # results: # default is test-reports
          # Output filename including optional path
          # output: # optional
          
    - name: Complexity analysis using SCC
      uses: hdmsantander/scc-docker-action@3.0
      with:
        args: --exclude-dir obj --exclude-dir bin --include-ext cs --no-cocomo QuickPulse/
          
